# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-jessie-browsers-legacy
    steps:
      # - checkout
      - add_ssh_keys:
          fingerprints:
            - d7:ca:83:8c:49:1a:e4:bd:13:77:93:d9:78:67:d1:32
            - 92:99:09:43:77:16:70:28:b9:e1:90:db:b6:41:37:6d
      - run:
          name: Keyscan Github
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Clone GitHub repository
          command: git clone --branch author --single-branch git@github.com:ryansheehan/ryansheehan.github.io.git --depth=1
      - run:
          name: npm run deploy
          command: |
            cd ryansheehan.github.io
            pwd
            npm install --unsafe-perm
            git config user.email rsheehan@gmail.com
            git config user.name "CircleCI"
            npm run deploy -- --message "publishing latest posts [ci skip]"
workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          filters:
            branches:
              # only: author
              ignore: master
  weekly:
    triggers:
      - schedule:
          cron: "0 5 * * 3" # every wednesday at 5am https://crontab.guru/
          filters:
            branches:
              only: author
    jobs:
      - deploy